# Generated by Django 3.0.5 on 2020-08-19 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('name', models.CharField(default='', max_length=10)),
                ('msgs', models.CharField(default='', max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Police_data',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(default='', max_length=10)),
                ('middlename', models.CharField(default='', max_length=10)),
                ('lastname', models.CharField(default='', max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(default='', max_length=11)),
                ('mobile_no', models.IntegerField(default='')),
                ('passport_no', models.IntegerField(default='')),
                ('aadhar_no', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Police_Station_data',
            fields=[
                ('sho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('station_name', models.CharField(default='', max_length=50)),
                ('sho_fname', models.CharField(default='', max_length=20)),
                ('sho_lname', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('pincode', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(default='', max_length=10)),
                ('middlename', models.CharField(default='', max_length=10)),
                ('lastname', models.CharField(default='', max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(default='', max_length=11)),
                ('m_status', models.CharField(default='', max_length=8)),
                ('address', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('pincode', models.IntegerField(default='')),
                ('mobile_no', models.IntegerField(default='')),
                ('passport_no', models.IntegerField(default='')),
                ('aadhar_no', models.IntegerField(default='')),
                ('aadhar_image', models.ImageField(default='', upload_to='Fir_Project/media/Fir_app')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, unique=True, verbose_name='email address')),
                ('username', models.CharField(default='', max_length=15, unique=True)),
                ('is_user', models.BooleanField(default=False)),
                ('is_police', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_sho', models.BooleanField(default=False)),
                ('entry_date', models.DateField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
