# Generated by Django 3.0.5 on 2020-08-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='entry_date',
        ),
    ]
