# Generated by Django 3.0.5 on 2020-08-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0002_remove_myuser_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
