# Generated by Django 3.0.5 on 2020-08-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0004_auto_20200819_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='entrydate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
