# Generated by Django 3.0.5 on 2020-08-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0005_myuser_entrydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='mobile_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
