# Generated by Django 3.0.5 on 2020-08-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0006_auto_20200824_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='sho_id',
            field=models.IntegerField(default=1),
        ),
    ]
