# Generated by Django 3.0.5 on 2020-08-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0007_userdata_sho_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='sho_id',
            field=models.IntegerField(default=1),
        ),
    ]
