# Generated by Django 3.0.5 on 2020-08-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0008_auto_20200824_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='sho_id',
        ),
        migrations.AddField(
            model_name='police_data',
            name='sho_id',
            field=models.IntegerField(default=1),
        ),
    ]
