# Generated by Django 3.0.5 on 2020-08-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0011_auto_20200826_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ref_key',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
