# Generated by Django 3.0.5 on 2020-09-22 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0013_auto_20200829_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police_station_data',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fir_app.city'),
        ),
        migrations.AlterField(
            model_name='police_station_data',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fir_app.states'),
        ),
    ]
