# Generated by Django 3.0.5 on 2020-09-28 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0014_auto_20200922_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fir',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sho_name', models.CharField(default='', max_length=100)),
                ('crime_data', models.DateField()),
                ('crime_time', models.TimeField()),
                ('report_date', models.DateField(default=datetime.date.today)),
                ('report_time', models.TimeField(default=datetime.time(17, 53, 3, 860664))),
                ('crime_location', models.CharField(default='', max_length=300)),
                ('suspected_people', models.CharField(default='', max_length=300)),
                ('reasone_for_firdelay', models.CharField(default='', max_length=100)),
                ('stolen_things', models.CharField(default='', max_length=300)),
                ('stolen_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('death_report_number', models.CharField(default='', max_length=200)),
                ('additional_info', models.CharField(default='', max_length=300)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fir_app.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fir_app.states')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fir_app.Police_Station_data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fir_app.UserData')),
            ],
        ),
    ]
