# Generated by Django 3.0.5 on 2020-09-28 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0015_fir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='additional_info',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='crime_location',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='death_report_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='reasone_for_firdelay',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(17, 55, 51, 201494)),
        ),
        migrations.AlterField(
            model_name='fir',
            name='stolen_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='stolen_things',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='suspected_people',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
