# Generated by Django 3.0.5 on 2020-09-28 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0016_auto_20200928_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir',
            old_name='crime_data',
            new_name='crime_date',
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(18, 42, 19, 499606)),
        ),
    ]
