# Generated by Django 3.0.5 on 2020-09-28 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0017_auto_20200928_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(18, 59, 27, 680496)),
        ),
        migrations.AlterField(
            model_name='fir',
            name='stolen_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
