# Generated by Django 3.0.5 on 2020-09-28 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0018_auto_20200928_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(19, 19, 0, 55404)),
        ),
    ]
