# Generated by Django 3.0.5 on 2020-10-01 05:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0019_auto_20200928_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_data',
            name='duty_end_time',
            field=models.TimeField(default=datetime.time(10, 33, 36, 40643)),
        ),
        migrations.AddField(
            model_name='police_data',
            name='duty_start_time',
            field=models.TimeField(default=datetime.time(10, 33, 36, 40643)),
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(10, 33, 36, 42645)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='sho_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fir_app.Police_Station_data'),
        ),
    ]
