# Generated by Django 3.0.5 on 2020-10-02 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0020_auto_20201001_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='death_report_number',
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(16, 28, 47, 880912)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_end_time',
            field=models.TimeField(default=datetime.time(16, 28, 47, 874909)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_start_time',
            field=models.TimeField(default=datetime.time(16, 28, 47, 874909)),
        ),
    ]
