# Generated by Django 2.2.17 on 2020-12-11 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0022_auto_20201211_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy_fir',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(13, 31, 36, 985695)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_end_time',
            field=models.TimeField(default=datetime.time(13, 31, 36, 984585)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_start_time',
            field=models.TimeField(default=datetime.time(13, 31, 36, 984585)),
        ),
    ]
