# Generated by Django 3.1.4 on 2021-02-08 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0026_auto_20210208_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointofinterest',
            old_name='atitude',
            new_name='latitude',
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(20, 40, 11, 781888)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_end_time',
            field=models.TimeField(default=datetime.time(20, 40, 11, 780888)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_start_time',
            field=models.TimeField(default=datetime.time(20, 40, 11, 780888)),
        ),
    ]
