# Generated by Django 3.1.4 on 2021-02-08 15:37

import datetime
from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0027_auto_20210208_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pointofinterest',
            name='longitude',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='position',
            field=geoposition.fields.GeopositionField(default=None, max_length=42),
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(21, 7, 30, 31853)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_end_time',
            field=models.TimeField(default=datetime.time(21, 7, 30, 31853)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_start_time',
            field=models.TimeField(default=datetime.time(21, 7, 30, 31853)),
        ),
    ]
