# Generated by Django 3.1.4 on 2021-02-08 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0030_auto_20210208_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(21, 9, 20, 608224)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_end_time',
            field=models.TimeField(default=datetime.time(21, 9, 20, 607198)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_start_time',
            field=models.TimeField(default=datetime.time(21, 9, 20, 607198)),
        ),
    ]
