# Generated by Django 3.1.4 on 2021-02-09 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0032_auto_20210208_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(9, 2, 42, 603102)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_end_time',
            field=models.TimeField(default=datetime.time(9, 2, 42, 601107)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_start_time',
            field=models.TimeField(default=datetime.time(9, 2, 42, 601107)),
        ),
    ]
