# Generated by Django 3.1.4 on 2021-02-09 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0034_auto_20210209_0902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(9, 24, 23, 566948)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_end_time',
            field=models.TimeField(default=datetime.time(9, 24, 23, 565954)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_start_time',
            field=models.TimeField(default=datetime.time(9, 24, 23, 565954)),
        ),
    ]
