# Generated by Django 3.1.4 on 2021-02-09 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0038_auto_20210209_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], default=0, verbose_name='Gender')),
                ('language', models.PositiveSmallIntegerField(choices=[(0, 'CHINESE'), (1, 'SPANISH'), (2, 'ENGLISH'), (3, 'FRENCH'), (4, 'HINDI'), (5, 'ARABIC'), (6, 'RUSSIAN')], default=2, verbose_name='Language')),
                ('grades', models.CharField(max_length=2, verbose_name='Grades')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(14, 54, 29, 851212)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_end_time',
            field=models.TimeField(default=datetime.time(14, 54, 29, 850253)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_start_time',
            field=models.TimeField(default=datetime.time(14, 54, 29, 849455)),
        ),
    ]
