# Generated by Django 2.2.17 on 2021-02-16 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0042_auto_20210216_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummy_fir',
            name='dob',
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(10, 45, 20, 309473)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_end_time',
            field=models.TimeField(default=datetime.time(10, 45, 20, 308475)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_start_time',
            field=models.TimeField(default=datetime.time(10, 45, 20, 308475)),
        ),
    ]
