# Generated by Django 2.2.17 on 2021-02-20 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0043_auto_20210216_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='p_id',
        ),
        migrations.DeleteModel(
            name='dummy_fir',
        ),
        migrations.AlterField(
            model_name='fir',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(21, 55, 22, 624838)),
        ),
        migrations.AlterField(
            model_name='fir',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_end_time',
            field=models.TimeField(default=datetime.time(21, 55, 22, 622843)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_start_time',
            field=models.TimeField(default=datetime.time(21, 55, 22, 621846)),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
