# Generated by Django 2.2.17 on 2021-02-21 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0044_auto_20210220_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(9, 34, 26, 542171)),
        ),
        migrations.AlterField(
            model_name='fir',
            name='stolen_amount',
            field=models.CharField(blank=True, default=0.0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_end_time',
            field=models.TimeField(default=datetime.time(9, 34, 26, 541174)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_start_time',
            field=models.TimeField(default=datetime.time(9, 34, 26, 541174)),
        ),
    ]
