# Generated by Django 2.2.17 on 2021-02-21 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0045_auto_20210221_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(12, 14, 51, 432423)),
        ),
        migrations.AlterField(
            model_name='fir',
            name='station',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_end_time',
            field=models.TimeField(default=datetime.time(12, 14, 51, 431425)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_start_time',
            field=models.TimeField(default=datetime.time(12, 14, 51, 431425)),
        ),
    ]
