# Generated by Django 2.2.17 on 2021-04-02 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fir_app', '0046_auto_20210221_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fir',
            name='additional_info',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='report_time',
            field=models.TimeField(default=datetime.time(11, 11, 19, 545875)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_end_time',
            field=models.TimeField(default=datetime.time(11, 11, 19, 544875)),
        ),
        migrations.AlterField(
            model_name='police_data',
            name='duty_start_time',
            field=models.TimeField(default=datetime.time(11, 11, 19, 544875)),
        ),
    ]
